---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  namespace: nginx
  labels:
    app: nginx-app
    env: dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx-app
      env: dev
  template:
    metadata:
      labels:
        app: nginx-app
        env: dev
    spec:
      containers:
        - name: nginx
          image: shyamdascs/proxy:v2
          ports:
            - containerPort: 80

---
apiVersion: v1
kind: Service
metadata:
  name: nginx-service
  namespace: nginx
  labels:
    app: nginx-app
    env: dev
spec:
  type: NodePort
  selector:
    app: nginx-app
    env: dev
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
