apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  namespace: proxy
  labels:
    id: C0929653
    app: nginx-app
    env: dev
spec:
  replicas: 3
  selector:
    matchLabels:
      id: C0929653
  template:
    metadata:
      labels:
        id: C0929653
        app: nginx
        env: dev
    spec:
      containers:
      - name: nginx
        image: shyamdascs/nginx-inclass2:v1
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: nginx-service
  namespace: proxy
  labels:
    id: C0929653
    app: nginx-app
    env: dev
spec:
  selector:
    id: C0929653
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: NodePort
