apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.phpmyadmin.name }}-configmap
  labels:
    {{- toYaml .Values.phpmyadmin.labels | nindent 4 }}
data:
  {{- range $k, $v := .Values.phpmyadmin.configmap }}
  {{ $k }}: {{ $v | quote }}
  {{- end }}
