apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.phpmyadmin.name }}-secret
type: Opaque
data:
  {{- range $k, $v := .Values.phpmyadmin.secrets }}
  {{ $k }}: {{ $v | b64enc | quote }}
  {{- end }}
